In [3]:
import numpy as np

In [8]:
np.array(4)

array(4)

In [9]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [12]:
arr=np.array(my_list)

arr

array([1, 2, 3])

In [14]:
#Get 2d 3*3 array

my_mat=[[1,2,3],[4,5,6],[7,8,9]]

np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#ways to create arrays

upto_10=np.arange(0,10)

by_step=np.arange(0,10,3)  #Starting 0 upto 10 by 2 stepsize

In [20]:
upto_10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
by_step

array([0, 3, 6, 9])

In [25]:
#Get zeros only by using 

zero=np.zeros(5)

#get 5*5 vector
zeros_2d=np.zeros((5,5))   #1st one is row and 2nd is column

In [26]:
zeros_2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
#Get zeros only by using 

one=np.ones(5)

#get 5*5 vector
ones_2d=np.ones((5,5))   #1st one is row and 2nd is column

In [28]:
ones_2d


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
#linespace get evenly space points

np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [34]:
#Identity matrix
np.eye(6)



array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [35]:
#Generate random numbers

np.random.rand(5)

array([0.98232637, 0.64330966, 0.91905034, 0.35455737, 0.74188201])

In [38]:
np.random.randn(6,2)

array([[ 0.26931489, -1.73705889],
       [-1.13172519,  2.03891017],
       [ 0.42769509, -0.78074964],
       [ 0.89403426, -0.97525782],
       [ 0.53404978,  0.75977074],
       [-0.11097053, -1.45702984]])

In [40]:
#Get a random list of integers
np.random.randint(1,100)


np.random.randint(1,100,5)  #the 1st is lowest, 2nd is highest and the 3rd is the number of numbers

array([55, 44,  8, 20, 90])

In [41]:
arr=np.arange(25)

In [42]:
ranarr=np.random.randint(0,50,50)

In [45]:
arr

ranarr

array([ 5, 10, 46, 20, 26,  5,  5, 10, 31,  8, 23,  4, 27, 43, 19, 25, 45,
       45,  7,  8, 12, 33, 39,  7,  7, 31, 39, 30,  0, 26, 16,  6, 16, 26,
       42, 13, 12, 29, 45, 26, 23, 23,  7,  1, 44, 31, 16, 14,  2,  3])

In [46]:
#reshape is to arrange them into a specified matrix

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
    #Get max
    ranarr.max()

46

In [49]:
#Get min
ranarr.min()

0

In [51]:
#Get the index location of the minimum value
ranarr.argmax()

2

In [ ]:
arr.shape

In [59]:
from numpy.random import randint

In [60]:
randint(2,20)

7

In [61]:
#Numpy indexing and selection


app=np.arange(0,11)

In [65]:
#Index

app[7]

7

In [66]:
app[2:7]  #starting to ending

array([2, 3, 4, 5, 6])

In [69]:
app[5:]  #anything after specified parameter


array([ 5,  6,  7,  8,  9, 10])

In [70]:
app[:3]   #anything before specified number

array([0, 1, 2])

In [71]:
#change values of the array

app[0:5]=100

In [72]:
app

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [75]:
#reset
app=np.arange(0,11)
app

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
slice_app=app[0:5]

In [78]:
slice_app


slice_app[:]=5

In [79]:
slice_app

array([5, 5, 5, 5, 5])

In [80]:
app

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10])

In [81]:
#numpy does not keep copy but rather overwrites the changed values on the original array
#To copy we have to specify the copy method 


app_copy=app.copy()


In [82]:
app

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10])

In [83]:
app_copy

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10])

In [84]:
app_copy[:]=10

In [85]:
app

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10])

In [86]:
app_copy

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [88]:
#index a 2d matrix


ar=np.array([[5,10,15],[20,25,30],[30,35,40]])

ar

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [93]:
ar[0]      #Get the entire row




array([ 5, 10, 15])

In [96]:
ar[2][1]     #The first one is row and second is the column

35

In [97]:
ar[2,1]  #use this for being less prone to errors

35

In [98]:
ar[:2,1:]     #Grab everything by row 2 and everything after row 1


array([[10, 15],
       [25, 30]])

In [100]:
ar[1:,1:]

array([[25, 30],
       [35, 40]])

In [105]:
ar[1:2]

array([[20, 25, 30]])

In [106]:
#Conditional selection


arr=np.arange(1,11)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
bool_array=arr > 5

In [111]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [114]:
arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [115]:
arr[arr<5]

array([1, 2, 3, 4])

In [116]:
#Practice!   Practice!    Practice!


ar=np.arange(36).reshape(6,6)

In [117]:
ar

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [119]:
ar[1:3,2:4]

array([[ 8,  9],
       [14, 15]])

In [122]:
ar[1:2,2:5]

array([[ 8,  9, 10]])

In [131]:
ar[:,2:]

array([[ 2,  3,  4,  5],
       [ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29],
       [32, 33, 34, 35]])

In [132]:
#NUMPY OPERATIONS

arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [133]:
arr+arr

#Subtract - and multiply *

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [134]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [136]:
arr2=arr+100

In [137]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [138]:
arr2

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [139]:
arr*arr2

array([   0,  101,  204,  309,  416,  525,  636,  749,  864,  981, 1100])

In [143]:
arr/arr2

array([0.        , 0.00990099, 0.01960784, 0.02912621, 0.03846154,
       0.04761905, 0.05660377, 0.06542056, 0.07407407, 0.08256881,
       0.09090909])

In [145]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [146]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [148]:
np.max(arr)

10

In [149]:
np.log(arr)

<ipython-input-149-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])